// const AllProducts = [
//     {
//         id: 1,
//         name: "Betadine Mouthwash And Gargle 250 Ml",
//         brand: "Mundipharma",
//         category: "Personal Care",
//         subCategory: "Oral Care", 
//         price: 49.6,
//         image: "/images/product1.webp",
//         productRelated: [2, 3, 4, 5],
//         generics: "Povidone-Iodine",
//         usedFor: "Sore Throat & Oral Infections",
//         howItWorks: "It kills bacteria, viruses, and fungi that cause mouth and throat infections.",
//         precautions: "Do not use if you have thyroid disease or are allergic to iodine.",
//         sideEffects: "Local irritation, itching, or swelling of the mouth.",
//         discription: "Betadine Mouthwash and Gargle is an antiseptic solution used to treat sore throat and oral infections."
//     },
//     {
//         id: 2,
//         name: "Panadol Extra 500mg",
//         brand: "GSK Consumer Healthcare",
//         category: "Personal Care",
//         subCategory: "Pain Relief",  
//         price: 30.0,
//         image: "/images/product2.webp",
//         productRelated: [1, 3, 6, 7],
//         generics: "Paracetamol & Caffeine",
//         usedFor: "Headache, Migraine & Body Pain",
//         howItWorks: "Paracetamol blocks pain signals in the brain, while caffeine enhances its effectiveness.",
//         precautions: "Avoid taking other paracetamol-containing products simultaneously.",
//         sideEffects: "Sleeplessness, nervousness, or palpitations due to caffeine content.",
//         discription: "Panadol Extra 500mg is a pain relief medication that contains paracetamol and caffeine."
//     },
//     {
//         id: 3,
//         name: "Brufen 400mg Tablets",
//         brand: "Abbott Laboratories (Pak) Ltd",
//         category: "Sports Nutrition",
//         subCategory: "Supplements", 
//         price: 45.0,
//         image: "/images/product3.webp",
//         productRelated: [2, 4, 6, 7],
//         generics: "Ibuprofen",
//         usedFor: "Pain & Fever Relief",
//         howItWorks: "It relieves pain and reduces inflammation (swelling or redness).",
//         precautions: "If you get an infection while taking ibuprofen, tell your doctor. It may hide signs of infection.",
//         sideEffects: "Nausea, vomiting, dizziness, headache, stomach pain, heartburn.",
//         discription: "Brufen 400mg Tablets is an anti-inflammatory medication used to relieve pain and reduce inflammation."
//     },
//     {
//         id: 4,
//         name: "Otrivin Nasal Spray",
//         brand: "GSK",
//         category: "Sports Nutrition",
//         subCategory: "Energy Drinks", 
//         price: 55.0,
//         image: "/images/product4.webp",
//         productRelated: [3, 5, 6, 7],
//         generics: "Xylometazoline Hydrochloride",
//         usedFor: "Nasal Congestion",
//         howItWorks: "It narrows the blood vessels in the nasal passages to reduce swelling and congestion.",
//         precautions: "Do not use for more than 7 consecutive days to avoid rebound congestion.",
//         sideEffects: "Stinging or burning in the nose, sneezing, or nasal dryness.",
//         discription: "Otrivin Nasal Spray is a decongestant used to relieve nasal congestion caused by colds or allergies."
//     }
// ];


const AllProducts = [
    {
        id: 1,
        name: "Betadine Mouthwash And Gargle 250 Ml",
        brand: "Mundipharma",
        category: "Personal Care",
        subCategory: "Oral Care", 
        price: 49.6,
        image: "/images/product1.webp",
        productRelated: [2, 3, 7, 10],
        generics: "Povidone-Iodine",
        usedFor: "Sore Throat & Oral Infections",
        howItWorks: "It acts as an antiseptic that kills sensitive organisms like bacteria and fungi.",
        precautions: "Do not use if you have thyroid disorders. Avoid contact with eyes.",
        sideEffects: "Local irritation, skin rash, or redness in the mouth.",
        discription: "Betadine Mouthwash and Gargle is an antiseptic solution used to treat sore throat and oral infections."
    },
    {
        id: 2,
        name: "Panadol Extra 500mg",
        brand: "GSK Consumer Healthcare",
        category: "Personal Care",
        subCategory: "Pain Relief",  
        price: 30.0,
        image: "/images/product2.webp",
        productRelated: [3, 6, 9, 12],
        generics: "Paracetamol & Caffeine",
        usedFor: "Headache, Migraine & Fever",
        howItWorks: "Paracetamol blocks pain, while caffeine boosts its pain-relieving effect.",
        precautions: "Do not exceed 8 tablets in 24 hours. Avoid excessive caffeine intake.",
        sideEffects: "Insomnia, nervousness, or mild stomach upset.",
        discription: "Effective relief for tough pain while being gentle on the stomach."
    },
    {
        id: 3,
        name: "Brufen 400mg Tablets",
        brand: "Abbott Laboratories (Pak) Ltd",
        category: "Sports Nutrition",
        subCategory: "Supplements", 
        price: 45.0,
        image: "/images/product3.webp",
        productRelated: [2, 6, 12, 1],
        generics: "Ibuprofen",
        usedFor: "Inflammation & Body Pain",
        howItWorks: "It works by blocking the production of natural substances that cause inflammation.",
        precautions: "Take with food to avoid stomach irritation. Not recommended for asthma patients.",
        sideEffects: "Nausea, heartburn, stomach pain, or dizziness.",
        discription: "Commonly used for muscle pain, dental pain, and menstrual cramps."
    },
    {
        id: 4,
        name: "Otrivin Nasal Spray",
        brand: "Haleon",
        category: "Sports Nutrition",
        subCategory: "Energy Drinks", 
        price: 55.0,
        image: "/images/product4.webp",
        productRelated: [5, 10, 11, 2],
        generics: "Xylometazoline Hydrochloride",
        usedFor: "Nasal Congestion",
        howItWorks: "Narrows the blood vessels in the nose to reduce swelling and congestion.",
        precautions: "Do not use for more than 7 days. Can cause rebound congestion if overused.",
        sideEffects: "Dryness of the nose, sneezing, or temporary stinging.",
        discription: "Fast-acting relief from nasal congestion caused by colds or hay fever."
    },
    {
        id: 5,
        name: "Vicks VapoRub 50g",
        brand: "Procter & Gamble",
        category: "Nutrition & Supplements",
        subCategory: "Herbal Supplements", 
        price: 25.0,
        image: "/images/product5.webp",
        productRelated: [4, 7, 10, 11],
        generics: "Menthol & Camphor",
        usedFor: "Cough & Cold Relief",
        howItWorks: "Releases medicinal vapors that soothe nasal passages and quiet coughs.",
        precautions: "For external use only. Do not apply directly to nostrils or broken skin.",
        sideEffects: "Skin redness or mild irritation at the site of application.",
        discription: "A topical ointment used on the chest and throat to relieve cough."
    },
    {
        id: 6,
        name: "Advil 200mg Tablets",
        brand: "Pfizer",
        category: "Nutrition & Supplements",
        subCategory: "Vitamins", 
        price: 35.0,
        image: "/images/product6.webp",
        productRelated: [2, 3, 12, 9],
        generics: "Ibuprofen",
        usedFor: "Backache & Muscle Pain",
        howItWorks: "Reduces hormones that cause inflammation and pain in the body.",
        precautions: "Consult your doctor if you have heart disease or high blood pressure.",
        sideEffects: "Stomach upset, mild headache, or ringing in the ears.",
        discription: "Advil provides powerful pain relief for headaches and joint pain."
    },
    {
        id: 7,
        name: "Mucosolvan Syrup 100ml",
        brand: "Sanofi",
        category: "Personal Care",
        subCategory: "Cough Remedies",
        price: 22.50,
        image: "/images/product2.webp", 
        productRelated: [1, 5, 10, 11],
        generics: "Ambroxol Hydrochloride",
        usedFor: "Chest Congestion / Productive Cough",
        howItWorks: "Thins the mucus in the airways so it can be coughed out more easily.",
        precautions: "Consult a doctor if you have a history of stomach ulcers.",
        sideEffects: "Mild gastrointestinal disturbances or allergic reactions.",
        discription: "Provides relief from chesty coughs by clearing thick phlegm."
    },
    {
        id: 8,
        name: "Gaviscon Liquid 150ml",
        brand: "Reckitt Benckiser",
        category: "Home Healthcare",
        subCategory: "Glucose Meter",
        price: 85.0,
        image: "/images/product8.webp",
        productRelated: [9, 12, 2, 3],
        generics: "Sodium Alginate",
        usedFor: "Heartburn & Indigestion",
        howItWorks: "Forms a protective barrier on top of the stomach contents to prevent acid reflux.",
        precautions: "Wait 2 hours between taking Gaviscon and other medicines.",
        sideEffects: "Constipation or diarrhea in rare cases.",
        discription: "Fast and long-lasting relief from the pain of heartburn."
    },
    {
        id: 9,
        name: "Nexium 20mg Tablets",
        brand: "AstraZeneca",
        category: "Home Healthcare",
        subCategory: "Stomach Care",
        price: 120.0,
        image: "/images/product7.webp",
        productRelated: [8, 12, 2, 3],
        generics: "Esomeprazole",
        usedFor: "Acid Reflux & Ulcers",
        howItWorks: "Decreases the amount of acid produced in the stomach.",
        precautions: "Swallow whole; do not crush or chew. Take 1 hour before meals.",
        sideEffects: "Headache, diarrhea, or dry mouth.",
        discription: "Used to treat symptoms of gastroesophageal reflux disease (GERD)."
    },
    {
        id: 10,
        name: "Strepsils Honey & Lemon",
        brand: "Reckitt",
        category: "Personal Care",
        subCategory: "Oral Care",
        price: 15.0,
        image: "/images/product1.webp",
        productRelated: [1, 7, 5, 4],
        generics: "2,4-Dichlorobenzyl alcohol",
        usedFor: "Sore Throat Relief",
        howItWorks: "Contains antiseptics that help kill the bacteria associated with mouth and throat infections.",
        precautions: "Not suitable for children under 6 years of age.",
        sideEffects: "Rarely, tongue soreness or allergic reactions.",
        discription: "Soothing effective relief for sore throats."
    },
    {
        id: 11,
        name: "Panadol CF (Cold & Flu)",
        brand: "GSK",
        category: "Personal Care",
        subCategory: "Cold Relief",
        price: 45.0,
        image: "/images/product2.webp",
        productRelated: [2, 4, 5, 7],
        generics: "Paracetamol & Pseudoephedrine",
        usedFor: "Flu Symptoms & Congestion",
        howItWorks: "Combines pain relief with a decongestant to clear blocked noses.",
        precautions: "May cause sleeplessness. Do not take with other cold medicines.",
        sideEffects: "Increased heart rate, nervousness, or dry mouth.",
        discription: "Multi-symptom relief for cold and flu including fever and congestion."
    },
    {
        id: 12,
        name: "Voltaren Emulgel 50g",
        brand: "GSK / Novartis",
        category: "Sports Nutrition",
        subCategory: "Topical Pain",
        price: 95.0,
        image: "/images/product3.webp",
        productRelated: [3, 6, 2, 9],
        generics: "Diclofenac Diethylammonium",
        usedFor: "Joint & Muscle Pain",
        howItWorks: "Penetrates deep into the skin to provide anti-inflammatory relief directly at the source.",
        precautions: "Do not apply to open wounds or infected skin. Wash hands after use.",
        sideEffects: "Skin rash, itching, or redness at the application site.",
        discription: "Clinically proven to provide effective relief from joint pain and inflammation."
    }
];



const Allcategory = [
  {
    id: 1,
    name: "Beauty Care",
    description: "Premium collection of skincare, hair care, and cosmetics.",
    icon: "fas fa-spa",
    subCategories: ["Skincare", "Hair Care", "Cosmetics"]
  },
  {
    id: 2,
    name: "Sports Nutrition",
    description: "Fuel your performance with high-quality protein and supplements.",
    icon: "fas fa-dumbbell",
    subCategories: ["Protein Powder", "Energy Drinks", "Supplements"]
  },
  {
    id: 5,
    name: "Personal Care",
    description: "Daily hygiene and personal care essentials for the whole family.",
    icon: "fas fa-pump-soap",
    subCategories: ["Oral Care", "Body Wash", "Deodorants"]
  }
];

export { AllProducts, Allcategory };
